### ISSUE TITLE
$form->text('label', '标签') ,this will cause the input box to be invisible

### ISSUE THREAD

**Issue by yangzuwei** [z-song/laravel-admin#2306]
- Laravel Version: 5.6.28
- PHP Version: 7.1.16
- Laravel-admin: 1.5.15

### Description:
his will cause the input box to be invisible

**Comment by z-song** [comment]
在`public/vendor/laravel-admin/laravel-admin/laravel-admin.css`中加入css覆盖掉AdminLte的样式
```css
input.label {
    display: inherit !important;
    padding: 6px 12px !important;
    font-size: 14px !important;
    font-weight: inherit !important;
    line-height: 1.42857143 !important;
    color: #555 !important;
    text-align: inherit !important;
    white-space: inherit !important;
    vertical-align: inherit !important;
    border-radius: inherit !important;
}
```
